services:
  postgres:
    image: postgres:16
    container_name: spring-security-poc-db
    environment:
      POSTGRES_DB: jwt-auth-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
